src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'Offres', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $ref_entreprise = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'Offres', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeContrat $ref_type_contrat = null;

    #[ORM\Column(nullable: true)]
    private ?bool $valid = false;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: ReponseOffre::class)]
    private Collection $response_offres;

    public function __construct()
    {
        $this->response_offres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getRefEntreprise(): ?Entreprise
    {
        return $this->ref_entreprise;
    }

    public function setRefEntreprise(Entreprise $ref_entreprise): static
    {
        $this->ref_entreprise = $ref_entreprise;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getRefTypeContrat(): ?TypeContrat
    {
        return $this->ref_type_contrat;
    }

    public function setRefTypeContrat(TypeContrat $typeDeContrat): static
    {
        $this->ref_type_contrat = $typeDeContrat;

        return $this;
    }

    public function isValid(): ?bool
    {
        return $this->valid;
    }

    public function setValid(bool $valid): static
    {
        $this->valid = $valid;

        return $this;
    }

    /**
     * @return Collection<int, ReponseOffre>
     */
    public function getResponseOffres(): Collection
    {
        return $this->response_offres;
    }

    public function addResponseOffre(ReponseOffre $responseOffre): static
    {
        if (!$this->response_offres->contains($responseOffre)) {
            $this->response_offres->add($responseOffre);
            $responseOffre->setOffre($this);
        }

        return $this;
    }

    public function removeResponseOffre(ReponseOffre $responseOffre): static
    {
        if ($this->response_offres->removeElement($responseOffre)) {
            // set the owning side to null (unless already changed)
            if ($responseOffre->getOffre() === $this) {
                $responseOffre->setOffre(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;
use App\Repository\OffreRepository;
use App\Repository\EvenementRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_main')]
    public function index(
        OffreRepository     $offresrespo,
        EvenementRepository $evenementrepo,
        UserRepository      $userRepository,
        Security            $security
    ): Response
    {
        if ($security->isGranted("ROLE_ADMIN")) {
            $users = $userRepository->findAll();
        }
        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'offres' => $offresrespo->findAll(),
            'evenements' => $evenementrepo->findAll(),
            'users' => $userRepository->findAll(),
        ]);
    }
}

templates/main/_viewEvenement.html.twig
<div class="form-box m-1 p-3 preview">
    <h3 class="text-center">
        {{ evenement.nom }}
    </h3>
    <p class="text-center">
        {{ evenement.description }}<br>
    </p>
    <p class="text-center inside-preview-section mt-2">
        {{ evenement.salle }}<br>
    </p>
    <p class="text-center inside-preview-section mt-2">
        5 réponses
    </p>
    <div class="row flex-nowrap content-edit-icon-card">
        <form class="col-4 icon" method="post" action="" onsubmit="return confirm('Etes vous sûrs de supprimer cet evenement?');">
            <input type="hidden" name="_token" value="">
            <button class="icon p-0 m-0 bg-transparent border-0" style="margin: 0 !important;">
                <img src="/assets/images/delete.png" alt="icon">
            </button>
        </form>
    </div>
</div>

templates/main/_viewOffre.html.twig
<div class="form-box m-1 p-3 preview">
    <h3 class="text-center">
        {{ offre.titre }}
    </h3>
    <p class="text-center">
        {{ offre.refTypeContrat.label }}<br>
    </p>
    <p class="text-center inside-preview-section mt-2">
        {{ offre.description }}<br>
    </p>
    <p class="text-center inside-preview-section mt-2">
        5 réponses
    </p>
    <div class="row flex-nowrap content-edit-icon-card">
        <form class="col-4 icon" method="post" action="" onsubmit="return confirm('Etes vous sûrs de supprimer cette offre?');">
            <input type="hidden" name="_token" value="">
            <a class="icon p-0 m-0 bg-transparent border-0" style="margin: 0 !important;" href="#">
                <img src="/assets/images/paper-plane.png" alt="icon">
            </a>
        </form>
    </div>
</div>

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue sur Studentgram!{% endblock %}


{% block body %}


    {% if not is_granted("ROLE_VALID") %}

        <style>
            body{
                background: url("assets/images/banner.jpg") no-repeat fixed center center;
                background-size: cover;
                backdrop-filter: brightness(0.5);
            }
        </style>

        <div class="d-flex align-items-center justify-content-center flex-column" style="height: 40vh;">
            <h1>Bienvenue sur studentgram</h1>
            <p>Ce site met en relation les entreprises et les étudiants</p>
            {% if is_granted("ROLE_USER") %}
            <p>Votre compte doit être validé !!!</p>
            {% endif %}

        </div>
        
        <div class="d-flex align-items-center justify-content-center" >
            <div style="height: 300px; width: 300px; background-color: #333; " class="m-5 rounded-3 d-flex justify-content-center align-items-center">
                <a href="https://www.lyceerobertschuman.com/" class="p-0">
                    <img src="assets/images/lprs.png" alt="LPRS" class="icon" style="max-width: 200px; max-height: 150px;">
                </a>
            </div>
            <div style="height: 300px; width: 300px; background-color: #333; " class="m-5 rounded-3 d-flex justify-content-center align-items-center">
                <a href="https://www.linkedin.com/in/ufa-robert-schuman-dugny/" class="p-0">
                    <img src="assets/images/linkedin.png" alt="linkedin" class="icon" style="max-width: 200px; max-height: 150px;">
                </a>
            </div>
        </div>

    {% endif %}
 
    


{% if is_granted("ROLE_ADMIN") or is_granted("ROLE_SUPERADMIN") %}
    {{ include('admin/user/_index.html.twig', {'users': users}) }}
{% endif %}

{% if (is_granted("ROLE_USER") or is_granted("ROLE_ENTREPRISE")) and not is_granted("ROLE_VALID") %}
    <!-- Message pour les utilisateurs en attente de validation -->
    <div class="presentation">
        <h1>Votre compte est en attente de validation</h1>

    </div>

{% endif %}

{% if (is_granted("ROLE_USER") or is_granted("ROLE_ENTREPRISE")) and is_granted("ROLE_VALID")%}
    <section class="preview-section">
        <div class="w-100">
            <h3>Offres</h3>
        </div>
        {% for offre in offres %}
            {{ include('main/_viewOffre.html.twig', {'offre': offre}) }}
        {% else %}
            <tr>
                <td colspan="5">pas d'offres disponibles</td>
            </tr>
        {% endfor %}
    </section>
{% endif %}

    {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_SUPERADMIN") %}
        {{ include('admin/user/_index.html.twig', {'users': users}) }}
    {% endif %}
    {% if (is_granted("ROLE_USER") or is_granted("ROLE_ENTREPRISE")) and is_granted("ROLE_VALID")%}
        <section class="preview-section">
            <div class="w-100">
                <h3>Evenements</h3>
            </div>
            {% for evenement in evenements %}
                {{ include('main/_viewEvenement.html.twig', {'evenement': evenement}) }}
            {% else %}
                <tr>
                    <td colspan="5">pas d'évènements disponibles</td>
                </tr>
            {% endfor %}
        </section>
    {% endif %}
{% endblock %}