src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_entreprise = null;

    #[ORM\Column(length: 255)]
    private ?string $fonction_employe = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    private ?string $cp = null;

    #[ORM\OneToOne(inversedBy: 'entreprise', cascade: ['persist', 'remove'])]
    private ?User $ref_user = null;

    #[ORM\OneToMany(mappedBy: 'ref_entreprise', cascade: ["persist", "remove"], targetEntity: Offre::class)]
    #[ORM\JoinColumn(nullable: true)]
    private Collection $offres;

    public function __construct()
    {
        $this->offres = new ArrayCollection();
    }

    /**
     * @return Collection<int, Offre>
     */
    public function getOffres(): Collection
    {
        return $this->offres;
    }
    public function __toString()
    {
        return $this->nom_entreprise;
    }



    public function addOffre(Offre $offre): self
    {
        if (!$this->offres->contains($offre)) {
            $this->offres[] = $offre;
            $offre->setRefEntreprise($this);
        }

        return $this;
    }

    public function removeOffre(Offre $offre): self
    {
        if ($this->offres->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getRefEntreprise() === $this) {
                $offre->setRefEntreprise(null);
            }
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;
        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): static
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getFonctionEmploye(): ?string
    {
        return $this->fonction_employe;
    }

    public function setFonctionEmploye(string $fonction_employe): static
    {
        $this->fonction_employe = $fonction_employe;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): static
    {
        $this->cp = $cp;

        return $this;
    }

    public function getRefUser(): ?User
    {
        return $this->ref_user;
    }

    public function setRefUser(?User $ref_user): static
    {
        $this->ref_user = $ref_user;

        return $this;
    }


    public function setOffres(?Offre $offres): static
    {
        $this->offres = $offres;

        return $this;
    }
}

src/Form/User/EditUserType.php
<?php

namespace App\Form\User;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class EditUserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('nom')
            ->add('prenom')
            ->add('commentaire')
            ->add('note')
            ->add('photo_profil', FileType::class, [
                'label' => 'photo de profil',
                'required' => false,
            ])
            ->add('plainPassword', PasswordType::class, [
                'required' => false,
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('entreprise', RegisterEntrepriseType::class,)
            ->add('etudiant', RegisterEtudiantType::class,)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/edit_user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EditUserController!{% endblock %}

{% block body %}
    <link rel="stylesheet" href="/assets/css/commentbutton.css">
    <script src="/assets/js/registrationForm/updatepp.js"></script>
    <script src="/assets/js/registrationForm/switchcompany.js"></script>
    <script src="/assets/js/registrationForm/map.js" defer></script>
    <script src="/assets/js/comment/comment.js" defer></script>

    <!-- Map integration -->
    <link rel="stylesheet" href="//cdn.leafletjs.com/leaflet-0.7.3/leaflet.css"/>
    <script src="//cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>


    <section class="position-absolute w-100">
	</section>
	<section class="hero d-flex align-items-center" id="hero" style="padding-top:90px; height: auto; min-height: 100vh;">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-lg-6 d-flex flex-column justify-content-center" style="display: flex;align-items: center; padding: 30px;">
					<h1 data-aos="fade-up" class="aos-init aos-animate">Inscription</h1>
					<h2 data-aos="fade-up" data-aos-delay="400" class="aos-init aos-animate">ou</h2>
					<div data-aos="fade-up" data-aos-delay="600" class="aos-init aos-animate">
						<div class="text-center text-lg-start">
							<a href="/register" class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
								<span>Retour acceuil</span>
								<img alt="arrow" src="/assets/images/arrow.png" height="30px" class="arrow">
							</a>
						</div>
					</div>
				</div>


				<div class="col-lg-6 contact">
					<div class="php-email-form" name="registration_form" style="height: auto; background-color: #ffffff08; padding: 30px; margin: 30px; ">
						{{ form_start(form) }}
						<div class="row gy-4 counts" style="padding:10px; ">
							<div class="col-md-12 d-flex justify-content-center align-items-center">
								<div class="login" style="height: 100px; width: 100px; padding: 10px">
									<div class="w-100 h-100 d-flex justify-content-center align-items-center" style="background: url({{ (app.user.getPhotoProfil())?app.user.getPhotoProfil():'/assets/images/user1.png' }}); background-size: contain;" id="inputPP">
										<input type="file" name="{{ field_name(form.photo_profil) }}" class="form-control w-100 h-100 position-absolute" style="filter: opacity(0);" accept="image">
									</div>
								</div>
							</div>
							{% if is_granted('ROLE_ENTREPRISE') %}

								<div class="col-md-12 row m-0 mt-3 p-0" id="companyform" style="visibility: visible;height: fit-content;filter: opacity(1);">

									<div class="col-md-12">
										<input value="{{ app.user.entreprise.adresse }} {{ app.user.entreprise.cp }} {{ app.user.entreprise.ville }}" id="adress" type="text" class="form-control inputcompany" name="adress" placeholder="Adresse">
										<div class="count-box" style="margin: 20px 20px 0; padding: 10px; width: fit-content; font-size: 0.5em;">
											<span id="adresstext" style="font-size: 2.2em;">Adresse</span>
										</div>
										<input value="" id="rue" type="hidden" class="form-control inputcompany" name="{{ field_name(form.entreprise.adresse) }}" placeholder="Adresse">
										<input value="" id="cp" type="hidden" class="form-control inputcompany" name="{{ field_name(form.entreprise.cp) }}" placeholder="Adresse">
										<input value="" id="ville" type="hidden" class="form-control inputcompany" name="{{ field_name(form.entreprise.ville) }}" placeholder="Adresse">
									</div>

									<div class="col-md-6 mt-3">
										<input value="{{ app.user.entreprise.nomEntreprise }}" type="text" class="form-control inputcompany" id="registration_form_nom" name="{{ field_name(form.entreprise.nom_entreprise) }}" maxlength="255" placeholder="Company-Name">
									</div>

									<div class="col-md-6 mt-3">
										<input value="{{ app.user.entreprise.fonctionEmploye }}" type="text" class="form-control inputcompany" id="registration_form_prenom" name="{{ field_name(form.entreprise.fonction_employe) }}" maxlength="255" placeholder="Position-Held">
									</div>
								</div>
								{% endif %}
							<div class="col-md-6">
								<input value="{{ app.user.nom }}" type="text" class="form-control" id="registration_form_nom" name="{{ field_name(form.nom) }}" maxlength="255" placeholder="Family-Name" autocomplete="family-name" required="">
							</div>

							<div class="col-md-6">
								<input value="{{ app.user.prenom }}" type="text" class="form-control" id="registration_form_prenom" name="{{ field_name(form.prenom) }}" maxlength="255" placeholder="Name" autocomplete="given-name" required="">
							</div>

							<div class="col-md-12">
								<input value="{{ app.user.email }}" type="email" class="form-control" id="registration_form_email" name="{{ field_name(form.email) }}" placeholder="E-mail" autocomplete="email" maxlength="180" required="required">
							</div>

							{% if not is_granted('ROLE_ENTREPRISE') %}
							<div class="col-md-6 optionalform" id="etudiantform"  style="filter: opacity(1); visibility: visible;">
								<select name="{{ field_name(form.etudiant.domaine_etude) }}" class="form-control selectinput etudiantinput" required="required">
									<option value="" disabled selected hidden>Domaine d'étude</option>
									<option value="option1">Option 1</option>
									<option value="option2">Option 2</option>
									<option value="option3">Option 3</option>
								  </select>
							</div>
							{% endif %}

							<div class="col-md-6">
								<input value="" type="password" id="registration_form_plainPassword" name="{{ field_name(form.plainPassword) }}" autocomplete="new-password" class="form-control" placeholder="Password">
							</div>


							<div class="comment">
								<div>
									<button type="button" class="bookmarkBtn" id="viewCommentCard" onclick="viewcard()" name="">
										<span class="IconContainer">
											<svg fill="white" viewbox="0 0 512 512" height="1em">
												<path d="M123.6 391.3c12.9-9.4 29.6-11.8 44.6-6.4c26.5 9.6 56.2 15.1 87.8 15.1c124.7 0 208-80.5 208-160s-83.3-160-208-160S48 160.5 48 240c0 32 12.4 62.8 35.7 89.2c8.6 9.7 12.8 22.5 11.8 35.5c-1.4 18.1-5.7 34.7-11.3 49.4c17-7.9 31.1-16.7 39.4-22.7zM21.2 431.9c1.8-2.7 3.5-5.4 5.1-8.1c10-16.6 19.5-38.4 21.4-62.9C17.7 326.8 0 285.1 0 240C0 125.1 114.6 32 256 32s256 93.1 256 208s-114.6 208-256 208c-37.1 0-72.3-6.4-104.1-17.9c-11.9 8.7-31.3 20.6-54.3 30.6c-15.1 6.6-32.3 12.6-50.1 16.1c-.8 .2-1.6 .3-2.4 .5c-4.4 .8-8.7 1.5-13.2 1.9c-.2 0-.5 .1-.7 .1c-5.1 .5-10.2 .8-15.3 .8c-6.5 0-12.3-3.9-14.8-9.9c-2.5-6-1.1-12.8 3.4-17.4c4.1-4.2 7.8-8.7 11.3-13.5c1.7-2.3 3.3-4.6 4.8-6.9c.1-.2 .2-.3 .3-.5z"></path>
											</svg>
										</span>
										<p class="text">Comment</p>
									</button>
								</div>
								<div class="card" id="viewCard" style="height: 0px; filter: opacity(0); visibility: hidden; margin: 0; padding: 0;">

									<div class="rating col-lg-12">
										<input type="radio" id="star-1" name="{{ field_name(form.note) }}" value="1"{{ ( app.user.note == 1 )?' checked':'' }}>
										<label for="star-1">
											<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24">
												<path pathlength="360" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z"></path>
											</svg>
										</label>
										<input type="radio" id="star-2" name="{{ field_name(form.note) }}" value="2"{{ ( app.user.note == 2 )?' checked':'' }}>
										<label for="star-2">
											<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24">
												<path pathlength="360" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z"></path>
											</svg>
										</label>
										<input type="radio" id="star-3" name="{{ field_name(form.note) }}" value="3"{{ ( app.user.note == 3 )?' checked':'' }}>
										<label for="star-3">
											<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24">
												<path pathlength="360" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z"></path>
											</svg>
										</label>
										<input type="radio" id="star-4" name="{{ field_name(form.note) }}" value="4"{{ ( app.user.note == 4 )?' checked':'' }}>
										<label for="star-4">
											<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24">
												<path pathlength="360" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z"></path>
											</svg>
										</label>
										<input type="radio" id="star-5" name="{{ field_name(form.note) }}" value="5"{{ ( app.user.note == 5 )?' checked':'' }}>
										<label for="star-5">
											<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24">
												<path pathlength="360" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z"></path>
											</svg>
										</label>
									</div>

									<div class="col-md-12">
										<input value="{{ app.user.commentaire }}" type="text" name="{{ field_name(form.commentaire) }}" class="form-control" placeholder="Comment">
									</div>

								</div>
							</div>
							<div class="col-md-12 text-center">
								{% if form_errors(form) %}
									<div class="alert alert-danger">{{ form_errors(form) }}</div>
								{% endif %}
								<button class="btn btn-lg btn-primary" type="submit">Modifier</button>
							</div>

						</div>
						{{ form_widget(form._token) }}
						{{ form_end(form, {'render_rest': false}) }}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}